Sync MetalLB images to ghcr.io
canonical/k8s-snap pull request #513
Opened 2024-06-25 18:45 UTC by eaudetcobello

It's important to sync the images from ghcr.io to a platform that we control. This PR sync the MetalLB from their upstream source at quay.io to ghcr.io.

2024-06-25 19:47 UTC, neoaggelos approved these changes

2024-06-26 05:41 UTC, neoaggelos requested changes
Make sure to address https://github.com/canonical/k8s-snap/blob/78f406cdc3d83d962c2289fe825d364399ca317a/build-scripts/patches/moonray/apply#L11-L12 as part of this PR

2024-06-27 07:33 UTC, louiseschmidtgen approved these changes
Great work, lgtm!

2024-06-27 10:52 UTC, neoaggelos approved these changes

2024-06-27 11:11 UTC, merged