Enable error name linter
canonical/k8s-snap pull request #733
Opened 2024-10-11 18:37 UTC by bschimke95

The err checkers require some more refactoring, They are useful but I will consider them in a second iteration of the linting.

2024-10-16 16:15 UTC, eaudetcobello requested changes

2024-10-16 16:15 UTC, eaudetcobello commented on src/k8s/pkg/k8sd/setup/auth-token-webhook.conf
Should this file be part of the PR?

2024-10-16 16:15 UTC, eaudetcobello commented on src/k8s/pkg/k8sd/setup/k8s-apiserver-proxy.json
This file too? Also, missing newline at EOF

2024-10-17 19:04 UTC, bschimke95 commented on src/k8s/pkg/k8sd/setup/auth-token-webhook.conf
Thanks - they were created by the unittests and slipped through

2024-10-17 19:20 UTC, eaudetcobello approved these changes

2024-10-18 07:52 UTC, merged